In [1]:
import torch
from torch import nn
from torch.optim import SGD

In [2]:
# 定义device对象
# 准备数据
# 定义模型
# 实例化模型，实例化优化器，实例化loss
# 循环，梯度下降，参数更新

In [3]:
device = torch.device('cuda')# if torch.cuda.is_available() else 'cpu')
# 定义device对象

In [4]:
x = torch.rand([500,1])
x = x.to(device)
y_true = 3*x + 0.8
# 准备数据

In [5]:
class MyLinear(nn.Module):
    def __init__(self):
        super(MyLinear, self).__init__()
        self.linear = nn.Linear(1,1)
    def forward(self, x):
        out = self.linear(x)
        return out
# 定义模型

In [6]:
model = MyLinear().to(device)
optimizer = SGD(model.parameters(), 0.005)
loss_fn = nn.MSELoss()
# 实例化模型，实例化优化器，实例化loss

In [7]:
for i in range(20000):
    optimizer.zero_grad() #梯度置零
    y_predict = model(x) #得到预测值
    loss = loss_fn(y_predict, y_true) #获取loss值
    loss.backward() #反向传播
    optimizer.step()
    if i%1000==0:
        print(loss.item(), list(model.parameters()) )
# 循环，梯度下降，参数更新

11.262248992919922 [Parameter containing:
tensor([[-0.2999]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([-0.7315], device='cuda:0', requires_grad=True)]
0.08377828449010849 [Parameter containing:
tensor([[2.0238]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.3201], device='cuda:0', requires_grad=True)]
0.02133050002157688 [Parameter containing:
tensor([[2.5074]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([1.0625], device='cuda:0', requires_grad=True)]
0.005430859047919512 [Parameter containing:
tensor([[2.7515]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.9324], device='cuda:0', requires_grad=True)]
0.0013827432412654161 [Parameter containing:
tensor([[2.8746]], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.8668], device='cuda:0', requires_grad=True)]
0.0003520527679938823 [Parameter containing:
tensor([[2.9367]], device='cuda:0', requires_grad=True), Parameter